// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: api/uuid.proto

package api

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ServiceName   string                 `protobuf:"bytes,1,opt,name=service_name,json=serviceName,proto3" json:"service_name,omitempty"`
	ContainerName string                 `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
	NeedCount     int32                  `protobuf:"varint,3,opt,name=need_count,json=needCount,proto3" json:"need_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_api_uuid_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_uuid_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_api_uuid_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *FetchRequest) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

func (x *FetchRequest) GetNeedCount() int32 {
	if x != nil {
		return x.NeedCount
	}
	return 0
}

type UUIDRange struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ServiceId       int32                  `protobuf:"varint,1,opt,name=service_id,json=serviceId,proto3" json:"service_id,omitempty"`
	ContainerId     int32                  `protobuf:"varint,2,opt,name=container_id,json=containerId,proto3" json:"container_id,omitempty"`
	SequenceIdStart int32                  `protobuf:"varint,3,opt,name=sequence_id_start,json=sequenceIdStart,proto3" json:"sequence_id_start,omitempty"`
	SequenceIdEnd   int32                  `protobuf:"varint,4,opt,name=sequence_id_end,json=sequenceIdEnd,proto3" json:"sequence_id_end,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UUIDRange) Reset() {
	*x = UUIDRange{}
	mi := &file_api_uuid_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UUIDRange) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UUIDRange) ProtoMessage() {}

func (x *UUIDRange) ProtoReflect() protoreflect.Message {
	mi := &file_api_uuid_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UUIDRange.ProtoReflect.Descriptor instead.
func (*UUIDRange) Descriptor() ([]byte, []int) {
	return file_api_uuid_proto_rawDescGZIP(), []int{1}
}

func (x *UUIDRange) GetServiceId() int32 {
	if x != nil {
		return x.ServiceId
	}
	return 0
}

func (x *UUIDRange) GetContainerId() int32 {
	if x != nil {
		return x.ContainerId
	}
	return 0
}

func (x *UUIDRange) GetSequenceIdStart() int32 {
	if x != nil {
		return x.SequenceIdStart
	}
	return 0
}

func (x *UUIDRange) GetSequenceIdEnd() int32 {
	if x != nil {
		return x.SequenceIdEnd
	}
	return 0
}

type FetchReply struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*UUIDRange           `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchReply) Reset() {
	*x = FetchReply{}
	mi := &file_api_uuid_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchReply) ProtoMessage() {}

func (x *FetchReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_uuid_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchReply.ProtoReflect.Descriptor instead.
func (*FetchReply) Descriptor() ([]byte, []int) {
	return file_api_uuid_proto_rawDescGZIP(), []int{2}
}

func (x *FetchReply) GetItems() []*UUIDRange {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_api_uuid_proto protoreflect.FileDescriptor

const file_api_uuid_proto_rawDesc = "" +
	"\n" +
	"\x0eapi/uuid.proto\x12\x03api\"w\n" +
	"\fFetchRequest\x12!\n" +
	"\fservice_name\x18\x01 \x01(\tR\vserviceName\x12%\n" +
	"\x0econtainer_name\x18\x02 \x01(\tR\rcontainerName\x12\x1d\n" +
	"\n" +
	"need_count\x18\x03 \x01(\x05R\tneedCount\"\xa1\x01\n" +
	"\tUUIDRange\x12\x1d\n" +
	"\n" +
	"service_id\x18\x01 \x01(\x05R\tserviceId\x12!\n" +
	"\fcontainer_id\x18\x02 \x01(\x05R\vcontainerId\x12*\n" +
	"\x11sequence_id_start\x18\x03 \x01(\x05R\x0fsequenceIdStart\x12&\n" +
	"\x0fsequence_id_end\x18\x04 \x01(\x05R\rsequenceIdEnd\"2\n" +
	"\n" +
	"FetchReply\x12$\n" +
	"\x05items\x18\x01 \x03(\v2\x0e.api.UUIDRangeR\x05items25\n" +
	"\x04UUID\x12-\n" +
	"\x05Fetch\x12\x11.api.FetchRequest\x1a\x0f.api.FetchReply\"\x00B\x1eZ\x1cgithub.com/cnwinds/flake/apib\x06proto3"

var (
	file_api_uuid_proto_rawDescOnce sync.Once
	file_api_uuid_proto_rawDescData []byte
)

func file_api_uuid_proto_rawDescGZIP() []byte {
	file_api_uuid_proto_rawDescOnce.Do(func() {
		file_api_uuid_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_uuid_proto_rawDesc), len(file_api_uuid_proto_rawDesc)))
	})
	return file_api_uuid_proto_rawDescData
}

var file_api_uuid_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_api_uuid_proto_goTypes = []any{
	(*FetchRequest)(nil), // 0: api.FetchRequest
	(*UUIDRange)(nil),    // 1: api.UUIDRange
	(*FetchReply)(nil),   // 2: api.FetchReply
}
var file_api_uuid_proto_depIdxs = []int32{
	1, // 0: api.FetchReply.items:type_name -> api.UUIDRange
	0, // 1: api.UUID.Fetch:input_type -> api.FetchRequest
	2, // 2: api.UUID.Fetch:output_type -> api.FetchReply
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_uuid_proto_init() }
func file_api_uuid_proto_init() {
	if File_api_uuid_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_uuid_proto_rawDesc), len(file_api_uuid_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_uuid_proto_goTypes,
		DependencyIndexes: file_api_uuid_proto_depIdxs,
		MessageInfos:      file_api_uuid_proto_msgTypes,
	}.Build()
	File_api_uuid_proto = out.File
	file_api_uuid_proto_goTypes = nil
	file_api_uuid_proto_depIdxs = nil
}
