// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: api/uuid.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UUID_Fetch_FullMethodName = "/api.UUID/Fetch"
)

// UUIDClient is the client API for UUID service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UUIDClient interface {
	Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchReply, error)
}

type uUIDClient struct {
	cc grpc.ClientConnInterface
}

func NewUUIDClient(cc grpc.ClientConnInterface) UUIDClient {
	return &uUIDClient{cc}
}

func (c *uUIDClient) Fetch(ctx context.Context, in *FetchRequest, opts ...grpc.CallOption) (*FetchReply, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FetchReply)
	err := c.cc.Invoke(ctx, UUID_Fetch_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UUIDServer is the server API for UUID service.
// All implementations must embed UnimplementedUUIDServer
// for forward compatibility.
type UUIDServer interface {
	Fetch(context.Context, *FetchRequest) (*FetchReply, error)
	mustEmbedUnimplementedUUIDServer()
}

// UnimplementedUUIDServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUUIDServer struct{}

func (UnimplementedUUIDServer) Fetch(context.Context, *FetchRequest) (*FetchReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Fetch not implemented")
}
func (UnimplementedUUIDServer) mustEmbedUnimplementedUUIDServer() {}
func (UnimplementedUUIDServer) testEmbeddedByValue()              {}

// UnsafeUUIDServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UUIDServer will
// result in compilation errors.
type UnsafeUUIDServer interface {
	mustEmbedUnimplementedUUIDServer()
}

func RegisterUUIDServer(s grpc.ServiceRegistrar, srv UUIDServer) {
	// If the following call pancis, it indicates UnimplementedUUIDServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UUID_ServiceDesc, srv)
}

func _UUID_Fetch_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FetchRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UUIDServer).Fetch(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UUID_Fetch_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UUIDServer).Fetch(ctx, req.(*FetchRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UUID_ServiceDesc is the grpc.ServiceDesc for UUID service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UUID_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "api.UUID",
	HandlerType: (*UUIDServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Fetch",
			Handler:    _UUID_Fetch_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/uuid.proto",
}
