name: CI

on:
  push:
    branches: [ master ]
    tags: [ 'v*' ]
    paths-ignore: [ '**.md' ]
  pull_request:
    branches: [ master ]
    paths-ignore: [ '**.md' ]

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false

      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: latest

  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false

      - name: Get dependencies
        run: |
          go mod download
          go mod vendor

      - name: Run Tests
        run: go test -v ./...

  build:
    name: Build
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.23'
          cache: false

      - name: Build
        run: |
          go mod tidy
          go mod vendor
          go build -v -o flake

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: flake
          path: flake

  release:
    name: Create Release
    needs: [build]
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: flake

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: flake
          generate_release_notes: true
